[project]
site_name = "Kris Reynolds: MSc Portfolio"
site_url = "https://portfolio.krisreynolds.co.uk"
site_description = ""
site_author = "Kris Reynolds"
copyright = "&copy; 2026 Kris Reynolds"
docs_dir = "docs"
site_dir = "site"
extra_javascript = ["js/external-links.js"]
extra_css = ["stylesheets/extra.css"]
nav = [
  { "Home" = "index.md" },
  { "Business and Change Management" = [
      "ksb1-1.md",
      "ksb1-2.md",
      "ksb1-3.md",
      "ksb1-4.md",
      "ksb1-5.md",
      "ksb1-6.md"
  ]},
  { "Professional Competencies" = [
      "ksb2-1.md",
      "ksb2-2.md",
      "ksb2-3.md"
  ]}
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme]
features = [
    "navigation.top",
    "navigation.footer"
]

[project.extra.status]
notstarted = "Not yet started"
incomplete = "Incomplete"
complete = "Complete"

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.abbr]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.snippets]